### ISSUE TITLE
Time & date off with runit, despite being set properly according to the Gentoo Handbook

### ISSUE THREAD

**Issue by fusion809** [powerman/powerman-overlay#5]
Hi,

I followed the Gentoo Handbook with regard to setting up local time (on my glibc + runit system, not on the musl one) i.e. running:

```bash
echo "Australia/Brisbane" > /etc/localtime
emerge --config sys-libs/timezone-data
```

yet when I boot into Gentoo with runit I get these errors:

![virtualbox_gentoo linux glibc runit _21_11_2017_21_57_17](https://user-images.githubusercontent.com/4717341/33071989-6855c772-cf09-11e7-9943-53039c370b47.png)

I don't get this error when I follow the same technique with OpenRC or systemd. Any ideas how to fix this? 

Sorry if this turns out to not be a bug, it's just I'm stuck with what to do. 

Thanks for your time,
Brenton

**Comment by powerman** [comment]
It looks like this file should contain actual timezone data, not it's name. Not sure why Handbook tell you to do it this way, maybe `emerge --config sys-libs/timezone-data` does the trick of replacing file you've created with `echo` with actual data file. In short, check what this file contains (it should be a binary file) and if it's still text file then replace it using:
```
# cp /usr/share/zoneinfo/Australia/Brisbane /etc/localtime
```

As for error on screenshot - it's just a warning, usually happens on first boot (if you've installed Gentoo using system with another/wrong timezone) or because of using wrong timezone in BIOS (it should match one in /etc/localtime) and it's harmless.
